[package]
name = "chess-engine"
version = "0.1.0"
authors = ["bo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"
log4rs = "1.0"
nom = "7.1"
